# Generated by Django 2.2.28 on 2026-08-11 18:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Όνομα')),
                ('author_cv', models.TextField(verbose_name='Βιογραφικό')),
                ('position', models.IntegerField(default=main.models.Bios.get_number, verbose_name='Αριθμός Θέσης')),
                ('minified_cv', models.CharField(blank=True, max_length=255, verbose_name='Βιογραφικό')),
            ],
            options={
                'verbose_name_plural': 'Βιογραφικά',
                'verbose_name': 'Βιογραφικό',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='BodyText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Κείμενο')),
                ('author', models.CharField(max_length=255, verbose_name='Ποίος Το Είπε')),
                ('active', models.BooleanField(default=False, verbose_name='Ενεργό')),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ημερομηνία Αρχικής Δημοσίευσης')),
            ],
            options={
                'verbose_name_plural': 'Παραφορές',
                'verbose_name': 'Παραφορά',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Κατηγορίας')),
            ],
            options={
                'verbose_name_plural': 'Κατηγορίες',
                'verbose_name': 'Κατηγορία',
            },
        ),
        migrations.CreateModel(
            name='UpImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=250, upload_to='images/%Y/%m/%d/')),
                ('image_title', models.CharField(blank=True, max_length=255, verbose_name='Τίτλος')),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Ημερομηνία Ανάρτησης')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Εικόνες',
                'verbose_name': 'Εικόνα',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Κείμενο')),
                ('pub_date', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Ημερομηνία Ανάρτησης')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Τίτλος')),
                ('status', models.CharField(choices=[('p', 'Δημοσιευμένο'), ('d', 'Πρόχειρο')], default='d', max_length=1, verbose_name='Κατάσταση')),
                ('viewcount', models.IntegerField(default=0, verbose_name='Αριθμός Προβολών')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Αρθρογράφος')),
                ('category', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Category', verbose_name='Κατηγορία')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.UpImages', verbose_name='Εικόνα')),
            ],
            options={
                'verbose_name_plural': 'Δημοσιεύσεις',
                'verbose_name': 'Δημοσίευση',
                'ordering': ['-pub_date'],
            },
        ),
    ]
