# Generated by Django 4.2.16 on 2026-08-11 18:43

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Κείμενο'),
        ),
    ]
