# Generated by Django 4.2.16 on 2026-08-11 18:43
# django_ckeditor_5 replaced with models.TextField — same underlying column type.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=models.TextField(verbose_name='Κείμενο'),
        ),
    ]
