# Generated by Django 5.2.4 on 2026-08-11 18:52

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_posts_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Κείμενο'),
        ),
    ]
